## Numpy 

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python which is used for perform numerical operations 


Features :
1. Less Execution time
2. Less Memory 
3. Easy to execute compare to list

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [2]:
## initially Lets import numpy

import numpy as np
a=[1,2,3,4,5]

arr=np.array(a)
print(arr)
print(type(arr))



[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Indexing and Slicing 
print(b[2])
print(b[2:5])

2
[2 3 4]


In [4]:
# Creating Matrix
# 3 * 2 Matrix
c= np.array([[1,2],[3,2],[5,6]])
c

array([[1, 2],
       [3, 2],
       [5, 6]])

In [5]:
print(c.shape)
print(c.dtype)
print(c.ndim)
print(c.item)

(3, 2)
int32
2
<built-in method item of numpy.ndarray object at 0x00000222300ADDA0>


In [7]:
# Reshaping
c= np.array([[1,2],[3,2],[5,6]])
print(c)

print(c.reshape([1,6]))

print(c.reshape([6,1]))

print(c.reshape([2,3]))

[[1 2]
 [3 2]
 [5 6]]
[[1 2 3 2 5 6]]
[[1]
 [2]
 [3]
 [2]
 [5]
 [6]]
[[1 2 3]
 [2 5 6]]


In [9]:
#Easy perform operations using Numpy arrays 
a1=np.arange(10)
a2=np.arange(10)
print(a1+a2)
print(a1-a2)
print(a1*a2)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]


In [10]:
#Using Lists
L1 = range(10)
L2 = range(10)
add = [x+y for x,y in zip(L1,L2)]
diff = [x-y for x,y in zip(L1,L2)]
mul =  [x*y for x,y in zip(L1,L2)]

print(add)
print(diff)
print(mul)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [11]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.diag(range(3))

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [14]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])